# Generated by Django 3.0.5 on 2020-04-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('a', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='constant margin')),
                ('b', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='variable margin')),
                ('c', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='form parameter')),
                ('alpha', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='scope')),
                ('use_for_drafts', models.BooleanField(default=False, verbose_name='use for drafts ?')),
                ('use_for_products', models.BooleanField(default=False, verbose_name='use for products ?')),
            ],
            options={
                'verbose_name': 'price profile',
                'verbose_name_plural': 'price profiles',
            },
        ),
    ]
